networks:
  internal:
    driver: bridge

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    networks:
      - internal
    env_file: db.env
    volumes:
      - ./data/db/:/var/lib/mysql
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    networks:
      - internal
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    depends_on:
      - mariadb
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  api:
    image: sneaxiii/mawster-api:latest
#    build:
#      context: ./api/
#      dockerfile: api.Dockerfile
    container_name: api
    networks:
      - internal
    depends_on:
      - mariadb
    env_file:
      - api.env
    command: ["sh", "run.sh"]
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  front:
    image: sneaxiii/mawster-front:latest
#    build:
#      context: ./front
#      dockerfile: front.Dockerfile
    container_name: front
    networks:
      - internal
    depends_on:
      - api
    env_file:
      - front.env
    command: [ "sh", "run.sh" ]
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - internal
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --cleanup --label-enable
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

volumes:
  caddy_data:
  caddy_config:
