name: CI Pipeline

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release
permissions:
  contents: read
env:
  WORKDIR: ./api
  PYTHON_VERSION: ${{ vars.PYTHON_VERSION }}
jobs:
  lint-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          enable-cache: true
      - name: Install dev dependencies
        working-directory: ${{ env.WORKDIR }}
        run: uv sync --dev
      - name: Setup environment variables
        working-directory: ${{ env.WORKDIR }}
        run: mv api.env.example api.env
      - name: Run Ruff linter
        uses: astral-sh/ruff-action@v3
        with:
          src: ${{ env.WORKDIR }}
      - name: Run unit tests
        working-directory: ${{ env.WORKDIR }}
        run: uv run pytest tests/unit -v --tb=short
      - name: Run integration tests
        working-directory: ${{ env.WORKDIR }}
        run: uv run pytest tests/integration -v --tb=short
  changes:
    if: github.ref_name == 'release'
    name: Detect changed paths
    runs-on: ubuntu-latest
    needs: lint-test
    outputs:
      api: ${{ steps.filter.outputs.api }}
      front: ${{ steps.filter.outputs.front }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Detect changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            api:
              - 'api/**'
            front:
              - 'front/**'

  docker-api:
    if: needs.changes.outputs.api == 'true'
    environment: Api
    name: Docker Build & Push (API)
    runs-on: ubuntu-latest
    needs: changes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Generate timestamp tag
        run: echo "TAG=$(date +'${{ vars.TIME_TAG_FORMAT }}')" >> $GITHUB_ENV
      - name: Build and push Docker image for the api
        uses: docker/build-push-action@v6
        with:
          context: ./api
          file: ./api/api.Dockerfile
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/mawster-api:latest
            ${{ vars.DOCKERHUB_USERNAME }}/mawster-api:${{ env.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  docker-front:
    if: needs.changes.outputs.front == 'true'
    environment: Api
    name: Docker Build & Push (Front)
    runs-on: ubuntu-latest
    needs: changes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Generate timestamp tag
        run: echo "TAG=$(date +'${{ vars.TIME_TAG_FORMAT }}')" >> $GITHUB_ENV
      - name: Build and push Docker image for the front
        uses: docker/build-push-action@v6
        with:
          context: ./front
          file: ./front/front.Dockerfile
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/mawster-front:latest
            ${{ vars.DOCKERHUB_USERNAME }}/mawster-front:${{ env.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max